spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:~/Documents/fiap/fiapdatabase;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
  security:
    user:
      password: senha123
      name: admin
      roles: ADMIN
jwt:
  secret: f1aPs3cr37
  expire: 5
server:
  port : 8081