CREATE TABLE book (
    id bigint generated by default as identity,
    title varchar(500) not null,
    page_qty integer default null,
    isbn varchar(50) default null,
    release_date timestamp default null,
    creation_date timestamp default null,
    update_date timestamp default null,
    price decimal(19,2),
    author varchar(500) not null,
    primary key (id)
)